# Generated by Django 4.2.14 on 2024-08-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
