# Generated by Django 4.2.14 on 2024-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='note',
            field=models.TextField(),
        ),
    ]
