# Generated by Django 4.2.14 on 2024-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_mail_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('N', '未領取'), ('Y', '已領取'), ('O', '其他')], default='N', max_length=5),
            preserve_default=False,
        ),
    ]
