# Generated by Django 4.2.14 on 2024-08-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
