# Generated by Django 4.2.14 on 2024-08-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mysite.poll'),
        ),
    ]
