# Generated by Django 4.2.14 on 2024-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
