# Generated by Django 4.2.14 on 2024-08-27 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
