# Generated by Django 4.2.14 on 2024-08-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_poll_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='繳費明細')),
                ('amount', models.PositiveIntegerField(default=9000, verbose_name='管理費用')),
                ('due_date', models.DateField(verbose_name='應繳日期')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='繳費日期')),
                ('payway', models.CharField(choices=[('CS', '超商繳費'), ('ATM', 'ATM轉帳'), ('LP', 'Line Pay繳費')], max_length=5)),
                ('status', models.BooleanField(default=False, verbose_name='是否已繳費')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='mysite.profile')),
            ],
        ),
    ]
