# Generated by Django 4.2.14 on 2024-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_managementfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementfee',
            name='payway',
            field=models.CharField(blank=True, choices=[('CS', '超商繳費'), ('ATM', 'ATM轉帳'), ('LP', 'Line Pay繳費')], max_length=5, null=True),
        ),
    ]
