# Generated by Django 4.2.14 on 2024-08-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_managementfee_payway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('date', models.DateTimeField(verbose_name='活動日期')),
                ('location', models.CharField(max_length=50, verbose_name='活動地點')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('max_particioants', models.PositiveIntegerField(verbose_name='人數上限')),
            ],
        ),
    ]
