# Generated by Django 4.2.14 on 2024-08-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='活動日期'),
        ),
    ]
