# Generated by Django 4.2.14 on 2024-08-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0019_alter_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='報名日期')),
                ('is_registered', models.BooleanField(default=False, verbose_name='是否已報名')),
                ('participant_count', models.PositiveIntegerField(default=1, verbose_name='報名人數')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.activity', verbose_name='活動')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.profile', verbose_name='個人資料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
        ),
    ]
