# Generated by Django 4.2.14 on 2024-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_activityapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityapplication',
            name='current_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='目前報名人數'),
        ),
    ]
