# Generated by Django 4.2.14 on 2024-08-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_activityapplication_current_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityapplication',
            name='current_participants',
        ),
        migrations.AddField(
            model_name='activity',
            name='current_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='目前報名人數'),
        ),
    ]
