# Generated by Django 4.2.14 on 2024-08-29 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_remove_activityapplication_current_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapplication',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='報名人數'),
        ),
    ]
